Create salesforce-sfdx-tests.yml (#1)
* Create salesforce-sfdx-tests.yml

* add latest

* Update salesforce-sfdx-tests.yml

* Update salesforce-sfdx-tests.yml

* Update salesforce-sfdx-tests.yml

* use my image

* fix bash

* fix bash

* pytest infra my docker image

* run pytest in the CI

* remove publish junit

* use V4 and visualize tests

* use V4 and visualize tests

---------

Co-authored-by: Gabor Demeter <gabor.demeter@ebury.com>

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -10,7 +10,7 @@ on:
     paths:
       - 'Dockerfile'  # Only run if Dockerfile changes
   create:
-    tags:           # Only run when a new tag is created
+    tags:  # Only run when a new tag is created
 
 jobs:
   build:
@@ -18,11 +18,50 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v4
+      - uses: actions/checkout@v4
 
-    # Build the Docker image
-    - name: Build the Docker image
-      run: docker build . --file Dockerfile --tag sf_automation:latest
+      # Build the Docker image
+      - name: Build the Docker image
+        run: docker build . --file Dockerfile --tag sf_automation:latest
+
+  test:
+    needs: build
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v4
+
+      # Set up Python environment and run tests
+      - name: Set up and run tests
+        run: |
+          # Create a Python virtual environment and activate it
+          python3 -m venv venv
+          source venv/bin/activate
+          
+          # Install pytest, testinfra, and any other requirements
+          pip install pytest testinfra
+
+          # Run the pytest command to generate JUnit test result file
+          mkdir -p reports
+          pytest tests/docker/test_sf_automation.py --junitxml=reports/test-results.xml
+
+      # Upload test results for GitHub Actions
+      - name: Upload test results
+        uses: actions/upload-artifact@v4
+        with:
+          name: test-results
+          path: reports/test-results.xml
+
+        # Publish the JUnit Test Report (with annotations)
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure()  # Always run, even if the previous step fails
+        with:
+          report_paths: 'reports/test-results.xml'  # Path to your JUnit XML report
+          check_name: 'Docker Pytest'  # Name of the check
+          require_tests: true   # Fail the build if no tests are found
+          job_summary: true     # Include the test summary in the job summary
+          detailed_summary: true  # Provide a detailed summary of all tests
 
   push:
     # This job runs only when a new tag is created
@@ -30,20 +69,20 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v4
+      - uses: actions/checkout@v4
 
-    # Log in to DockerHub
-    - name: Log in to DockerHub
-      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
+      # Log in to DockerHub
+      - name: Log in to DockerHub
+        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
 
-    # Build the Docker image with the tag
-    - name: Build the Docker image with Tag
-      run: |
-        TAG_NAME=$(echo ${GITHUB_REF} | sed 's/refs\/tags\///')
-        docker build . --file Dockerfile --tag sf_automation:${TAG_NAME}
+      # Build the Docker image with the tag
+      - name: Build the Docker image with Tag
+        run: |
+          TAG_NAME=$(echo ${GITHUB_REF} | sed 's/refs\/tags\///')
+          docker build . --file Dockerfile --tag sf_automation:${TAG_NAME}
 
-    # Push the Docker image to DockerHub
-    -   name: Push the Docker image to DockerHub
+      # Push the Docker image to DockerHub
+      - name: Push the Docker image to DockerHub
         run: |
           TAG_NAME=$(echo "${GITHUB_REF}" | sed 's/refs\/tags\///')
           docker tag sf_automation:${TAG_NAME} ${{ secrets.DOCKERHUB_USERNAME }}/sf_automation:${TAG_NAME}
